### ISSUE TITLE
Add scrolling to Add Element page  to see description

### ISSUE THREAD

**Issue by VincentvonBueren92** [marcoklein/impromat#197]
**Description:**
* When creating a workshop, the added event formats lack scrolling functionality, causing usability issues when adding elements that exceed the visible area. 
* This issue aims to add scrolling to the individual event description to improve user experience and accommodate longer forms.

**Steps to Reproduce:**
* Navigate to https://impromat.app/workshop?dialog
* Click on the new workshop button
* Click on the **Add Element** button
* Currently, on the **Add Element**, the event descriptions in the cards containers exceed the visible area, there is no option to scroll, resulting in hidden and inaccessible content. 

**Expected Behavior:**
When the form content exceeds the visible area, a scroll bar should appear, allowing users to scroll and access all elements within the event card. 

**Relevant Links:**
* https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling

**Acceptance Criteria:**
* Scrollbar is added to event description cards that are overflowing
* Testing is implemented to assert correct behavior

**Additional Notes:**
* This behavior can not only be seen in Add Element page, but also on pages like: workshop overview [https://impromat.app/workshop]. I would create a separate tickets that tackle the same issue and take the solution/completion of this ticket as reference

**Screenshots or Code Snippets:**
* Add Element page
* Workshop overview

![Screenshot 2023-06-26 at 09 06 34](https://github.com/marcoklein/impromat/assets/38384094/dd997160-dbe3-4597-9db2-c9d76060b887)

![Screenshot 2023-06-26 at 09 03 23](https://github.com/marcoklein/impromat/assets/38384094/752fadc8-f2dd-4d14-891b-37303622f268)

**Comment by marcoklein** [comment]
Thank you for reporting this. I wonder if scrolling within cards is the way to go because then the scrolling through the whole page might be interrupted by the smaller scrolls within individual cards. I especially see a risk on mobile devices for this.

Have to try either way to see how it affects UX.
